version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-dfp
    versions:
    - 0.19.0
    - 0.20.0
  - dependency-name: directory-tree
    versions:
    - 2.2.5
    - 2.2.6
    - 2.2.7
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
